### ISSUE TITLE
Things to do for new contributors

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#439]
[Vispy is a high-performance visualization library in Python](http://vispy.org). Although working on the internals of Vispy requires knowing some OpenGL and GLSL, there's a lot of work to do for general Python/NumPy programmers. Web developers are also welcome to contribute (JavaScript, backbone.js, WebGL).

The following list contains tasks that new-comers can tackle without much knowledge of OpenGL/GLSL (see also [the list of issues on GitHub](https://github.com/vispy/vispy/labels/euroscipy2014)).
- [x] Work on the headless mode (#78)
- [x] Porting @rougier's collections to Vispy (#410)
- [x] Adding a few examples (#420 #434 #435)
- [x] Implement ffmpeg binding (#419)
- [Independent features](https://github.com/vispy/vispy/issues?q=is%3Aopen+label%3A%22type%3A+independent-feature%22+label%3Aeuroscipy2014) (mainly for new contributors):
  - [ ] #123: path animations
  - [ ] #131: high-level interactions (hard)
  - [ ] #132: serialization of binary data in PNG images (hard)
  - [x] #194: geometry routines useful for visualization
  - [ ] #367: collision-free configurations
  - [x] #648: implement more colormaps
  - [ ] #415: generating distinct colors
- [Dependent features](https://github.com/vispy/vispy/issues?q=is%3Aopen+label%3Aeuroscipy2014+label%3A%22type%3A+feature%22) (need some knowledge of Vispy and OpenGL):
  - [x] #157: arcball camera
  - [ ] #158: SVG visuals (especially paths, Bézier curves, etc.)
  - [x] #181: exporting animations to videos (requires #419)
  - [x] #416: GLSL color transformation functions (just a matter of reusing existing GLSL code and putting it at the right place in Vispy)
  - [x] #417: implementing arrows and quiver plots

**Comment by kmuehlbauer** [comment]
I made the list in the issue using checkboxes and started checking, when resolved.

**Comment by GuillaumeFavelier** [comment]
If I'm not wrong, #78 and #417 can be checked, the corresponding issues have been closed.

**Comment by djhoese** [comment]
@GuillaumeFavelier Thanks. Checked.
