### ISSUE TITLE
Gloo refactoring (again?)

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#464]
I get the impression that the current implementation of gloo is a bit complicated. We keep finding bugs and sometimes the behavior is somewhat unexpected. I think this is mainly due to the fact that classes like Texture and Buffer operate in two modes: 
- Not storing any data locally and only passing data on to the GPU. The advantage is that it's relatively simple and as memory efficient as it can get.
- Store data locally. This has the advantage that it allows updating of arbitrary portions of the data. However, the data needs to be managed (e.g. when resizing), and it costs memory.

The fact that both modes are supported in a single class makes the code bulky and at times hard to follow. 

Until now I don't think we've ever needed the possibility to update arbitrary portions of the data in our higher levels. And when we will, it is something that can arguably also be taken care of at the Visual level. Therefore I'd like us to consider simplifying gloo and dropping support for storing local data. 

Related to https://github.com/lcampagn/vispy/commit/692f752198a40fc603cf0a7fb5c1fd2f244892a3#commitcomment-7526436 in #460.

This is post-0.3 material :) 

Things to be corrected, if possible:
1. [x] Implement #510 -- this will lead to a drastic change of gloo's internals, possibly for the better good :)
2. [x] Allow setting variables before `prepare()` is called / anytime / before `draw`.
3. [x] #450 How `size` is set / handled, although #460 probably fixes that problem.
4. [x] #338 Allowing creation of Texture without memory (e.g., for Framebuffer), 
5. [x] #407 Uniform with default values are not correctly parsed during Program initialization
6. [x] #351 gloo.FrameBuffer.shape is not used
7. [ ] #345 Uniform arrays not supported in gloo
8. [x] Allow 1D arrays to be set (rather than requiring them to be Nx1. See e.g. raycasting and spacy
